### ISSUE TITLE
S updatem stream resolveru na 1.6.42 přestaly fungovat titulky

### ISSUE THREAD

**Issue by zbyna** [kodi-czsk/plugin.video.videacesky.cz#8]
Log:

```
17:48:45 T:5116  NOTICE: ["Initializing provider videacesky.cz with settings {'downloads': '', 'quality': '1'}"]
17:48:46 T:5116  NOTICE: [u'Found resolvable http://www.youtube.com/watch?v=8qubNFRMjYQ']
17:48:46 T:5116  NOTICE: [u'Resolving http://www.youtube.com/watch?v=8qubNFRMjYQ']
17:48:46 T:5116  NOTICE: ["Using resolver 'youtube'"]
17:48:47 T:5116  NOTICE: ['filtering by quality setting 1']
17:48:47 T:5116   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: load_subtitles() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\plugin.video.videacesky.cz\default.py", line 142, in <module>
                                                VideaceskyXBMCContentProvider(videacesky.VideaceskyContentProvider(tmp_dir=xbmc.translatePath(__addon__.getAddonInfo('profile'))), settings, __addon__).run(params)
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 71, in run
                                                return self.play({'url':params['play'],'info':params})
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\plugin.video.videacesky.cz\default.py", line 95, in play
                                                xbmcutil.load_subtitles(stream['subs'])
                                            TypeError: load_subtitles() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--
```

Systém:

```
17:46:38 T:3220  NOTICE: Starting Kodi (16.1 Git:20160424-c327c53). Platform: Windows NT x86 32-bit
17:46:38 T:3220  NOTICE: Using Release Kodi x32 build
17:46:38 T:3220  NOTICE: Kodi compiled Apr 24 2016 by MSVC 180040629 for Windows NT x86 32-bit version 6.0 (0x06000000)
17:46:38 T:3220  NOTICE: Running on MSI MS-7681 with Windows 7 SP1, kernel: Windows NT x86 64-bit version 6.1
17:46:38 T:3220  NOTICE: Host CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 4 cores available
17:46:38 T:3220  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
17:46:38 T:3220  NOTICE: Running with administrator rights
17:46:38 T:3220  NOTICE: Aero is enabled
```

**Comment by zbyna** [comment]
Jednoduchý patch:
https://gist.github.com/anonymous/9272d16fc58aa6fc17b90092a3d8af76

**Comment by mx3L** [comment]
Omylom som znefunkcnil viac pluginov, tu je oprava ktora vyriesi problem:
https://github.com/kodi-czsk/script.module.stream.resolver/pull/40
